baseurl = "https://thomascoopman.eu"
languageCode = "en-us"
title = "Thomas Coopman - Infinite Tree"
MetaDataFormat = "toml"
theme = "infinitetree"
paginate = 10
pygmentsuseclasses = false
pygmentsstyle = "pastie"
PygmentsCodeFences = true
disqusShortname = "thomascoopmaneu"

[author]
name = "Thomas Coopman"

[permalinks]
# Optional. Change the permalink format for the 'post' content type.
# The format shown here is the same one Jekyll/Octopress uses by default.
post = "/blog/:year/:month/:day/:title/"

[taxonomies]
# Optional. Use if you want tags and lists.
category = "categories"
tag = "tags"

#
# All parameters below here are optional and can be mixed and matched.
#
[[menu.main]]
identifier = "blog"
name = "Blog"
url = "/"
weight = -120
[[menu.main]]
name = "Twitter timeline"
pre = "<h3>Follow me</h3>"
url = "https://twitter.com/tcoopman"
weight = 100
[[menu.main]]
name = "Github repos"
url =  "https://github.com/tcoopman/"
weight = 101
[[menu.main]]
name = "Bitbucket repos"
url = "https://bitbucket.org/tcoopman/"
weight = 102
[[menu.main]]
name = "Linkedin"
url =  "https://www.linkedin.com/in/thomas-coopman-a6860622?trk=hp-identity-name"
weight = 103
[[menu.main]]
name = "Google Plus"
url =  "https://plus.google.com/u/0/109624499308077610663"
weight = 104

[params]
author = "Thomas Coopman"
authorlocation = "Belgium"
authorwebsite = "https://infinitetree.eu"
bio = "Software Consultant"
cover = "images/cover_mistysun.jpg"
frontLogo = "images/front_logo_infinite_tree.png"
description = "Thomas Coopman - Software Consultant"
# If false display full article contents in blog index.
# Otherwise show description and 'read on' link to individual blog post page.
# Default (if omitted) is true.
truncate = true

# Hide estimated reading time for posts.
# Default (if omitted) is false.
hideReadingTime = false

# Changes sidebar background and link/accent colours.
# See below for more colour options.
# This also works: "theme-base-08 layout-reverse", or just "layout-reverse".

# Select a syntax highight.
# Check the static/css/highlight directory for options.
highlight = "sunburst"

# Optional additional custom CSS file URL, will override other styles.
# customCSS = "/css/images.css"

# Displays under the author name in the sidebar, keep it short.
# You can use markdown here.
tagline = "Software Consultant"

# Text for the top menu link, which goes the root URL for the site.
# Default (if omitted) is "Blog".
home = "Blog"

# Metadata used to drive integrations.
googleAnalytics = "UA-56701000-2"
twitterName = "tcoopman"
githubName = "tcoopman"


# Other social-like sidebar links
rss = true  # switch to true to enable RSS icon link


