baseurl = "https://thomascoopman.eu"
languageCode = "en-us"
title = "Thomas Coopman - Infinite Tree"
MetaDataFormat = "toml"
theme = "hyde-x"
paginate = 10
pygmentsuseclasses = false
pygmentsstyle = "pastie"
PygmentsCodeFences = true

[author]
    name = "Thomas Coopman"

[permalinks]
    # Optional. Change the permalink format for the 'post' content type.
    # The format shown here is the same one Jekyll/Octopress uses by default.
    post = "/blog/:year/:month/:day/:title/"

[taxonomies]
    # Optional. Use if you want tags and lists.
    category = "categories"

#
# All parameters below here are optional and can be mixed and matched.
#
[params]
    # If false display full article contents in blog index.
    # Otherwise show description and 'read on' link to individual blog post page.
    # Default (if omitted) is true.
    truncate = true

    # Hide estimated reading time for posts.
    # Default (if omitted) is false.
    hideReadingTime = false

    # Changes sidebar background and link/accent colours.
    # See below for more colour options.
    # This also works: "theme-base-08 layout-reverse", or just "layout-reverse".

    # Select a syntax highight.
    # Check the static/css/highlight directory for options.
    highlight = "sunburst"

    # Optional additional custom CSS file URL, will override other styles.
    customCSS = ""

    # Displays under the author name in the sidebar, keep it short.
    # You can use markdown here.
    tagline = "Software Consultant"

    # Text for the top menu link, which goes the root URL for the site.
    # Default (if omitted) is "Blog".
    home = "Blog"

    # Metadata used to drive integrations.
    googleAnalytics = "UA-56701000-2"

    # Sidebar social links, these must be full URLs.
    github = "https://github.com/tcoopman/"
    bitbucket = "https://bitbucket.org/tcoopman/"
    twitter = "https://twitter.com/tcoopman"
		linkedin = "https://www.linkedin.com/in/thomas-coopman-a6860622?trk=hp-identity-name"
		googleplus = "https://plus.google.com/u/0/109624499308077610663"

    # Other social-like sidebar links
    rss = true  # switch to true to enable RSS icon link


